In [3]:
import tensorflow as tf

hello = tf.constant('Hello')
sess = tf.Session()
print sess.run(hello)
version = tf.VERSION
print version

Hello
1.0.0-rc0


In [12]:
const_a = tf.constant([1,2,3,4,5,6], shape=(3,2))
print const_a

sess = tf.Session()
result_a = sess.run(const_a)
print result_a

Tensor("Const_10:0", shape=(3, 2), dtype=int32)
[[1 2]
 [3 4]
 [5 6]]


In [21]:
variable_a = tf.Variable([[1,1], [2,2]])
print variable_a

sess = tf.Session()
sess.run(variable_a.initializer)

result_a = sess.run(variable_a)
print result_a

Tensor("Variable_7/read:0", shape=(2, 2), dtype=int32)
[[1 1]
 [2 2]]


In [41]:
ph_a = tf.placeholder(tf.int16)
ph_b = tf.placeholder(tf.int16)

add_op = tf.add(ph_a, ph_b)

sess = tf.Session()
result_a = sess.run(add_op, feed_dict={ph_a:2, ph_b:3})
print result_a

5


In [31]:
import numpy as np
x_data = np.random.randn(3,3)
x = tf.constant(x_data, shape=(3,3))

sess = tf.Session()

print sess.run(x)
print x.dtype
print sess.run(tf.shape(x))
print sess.run(tf.rank(x))
print sess.run(tf.size(x))

[[ 0.26732964  1.12486039  1.39583735]
 [-0.33755196  0.7850476  -0.47840519]
 [ 1.49734985 -0.43131873  2.29519322]]
<dtype: 'float64'>
[3 3]
2
9


In [44]:
x = tf.placeholder(tf.float32, shape=(2,2))
y = tf.placeholder(tf.float32, shape=(2,2))

mat_a = np.arange(1,5).reshape(2,2)
print mat_a
mat_b = np.arange(11,15).reshape(2,2)
print mat_b

add_op = tf.add(x, y)
sess = tf.Session()


result_mat = sess.run(add_op, feed_dict={x:mat_a, y:mat_b})
print result_mat

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[ 12.  14.]
 [ 16.  18.]]


In [46]:
sub_op = tf.subtract(x, y)

result_mat = sess.run(sub_op, feed_dict={x:mat_a, y:mat_b})
print result_mat

[[-10. -10.]
 [-10. -10.]]


In [47]:
matmul_op = tf.matmul(x, y)

result_mat = sess.run(matmul_op, feed_dict={x:mat_a, y:mat_b})
print result_mat

[[ 37.  40.]
 [ 85.  92.]]


In [48]:
mul_op = tf.multiply(x, y)
result_mat = sess.run(mul_op, feed_dict={x:mat_a, y:mat_b})
print result_mat

[[ 11.  24.]
 [ 39.  56.]]


In [57]:
x_data = np.arange(1,5).reshape(2,2)
x = tf.placeholder(tf.float32, shape=(2,2))
a1 = tf.reduce_sum(x)
print a1
a2 = tf.reduce_sum(x, 0)
print a2
a3 = tf.reduce_sum(x, 1)
sess = tf.Session()
print sess.run(x, feed_dict={x:x_data})
print sess.run(tf.reduce_sum(x), feed_dict={x:x_data})
print sess.run(tf.reduce_sum(x, 0), feed_dict={x:x_data})

Tensor("Sum_13:0", shape=(), dtype=float32)
Tensor("Sum_14:0", shape=(2,), dtype=float32)
[[ 1.  2.]
 [ 3.  4.]]
10.0
[ 4.  6.]


In [63]:
data_a = np.random.randint(0, 100, (4,4))
const_a = tf.constant(data_a, dtype=tf.float32)
print const_a

argmin_op = tf.argmin(const_a, 1)
argmax_op = tf.argmax(const_a, 1)

# print sess.run(tf.argmin(x, 1), feed_dict={x: const_a})
with tf.Session() as sess:
  c, min, max = sess.run([const_a, argmin_op, argmax_op])
  print c
  print min
  print max

Tensor("Const_31:0", shape=(4, 4), dtype=float32)
[[ 96.  35.  47.  73.]
 [ 98.  79.  89.  46.]
 [ 14.  20.  22.  66.]
 [ 76.  32.  28.  23.]]
[1 3 0 3]
[0 0 3 0]


In [65]:
sess = tf.Session()
p = tf.constant([[0,0.25], [0.5,1]], dtype=tf.float32, shape=(2,2))
value = tf.clip_by_value(p, 1e-10, 1.0)

print p.eval(session=sess)
print value.eval(session=sess)

[[ 0.    0.25]
 [ 0.5   1.  ]]
[[  1.00000001e-10   2.50000000e-01]
 [  5.00000000e-01   1.00000000e+00]]


In [68]:
with tf.Session() as sess:
  p = tf.constant([[0,0.25], [0.5,1]], dtype=tf.float32, shape=(2,2))
  value = tf.clip_by_value(p, 1e-10, 1.0)
  print p.eval()
  print value.eval()

[[ 0.    0.25]
 [ 0.5   1.  ]]
[[  1.00000001e-10   2.50000000e-01]
 [  5.00000000e-01   1.00000000e+00]]


In [70]:
x = tf.random_normal(shape=(3,3))
sess = tf.Session()
y = sess.run(x)
print y

print sess.run(tf.random_normal(shape=(3,3)))

[[-0.32886976  0.27431205  1.88274431]
 [ 0.91664433  0.49180195  0.74493301]
 [ 0.06930567 -0.82327598 -3.85011458]]
[[ 0.93285948  0.09490342  0.50563556]
 [-1.0839386   0.55333292  0.29688841]
 [-0.34754691 -0.31674221 -0.46129054]]


In [72]:
x = tf.random_normal(shape=(5000,2))

sess = tf.Session()
y = sess.run(x)
print np.average(y)
print np.std(y)

0.00555553
0.994795
