In [5]:
import numpy as np
arr = np.array([1,5,10,4,11,22,21,11,10,1])
print arr

mat = arr.reshape([2,5])

print mat

[ 1  5 10  4 11 22 21 11 10  1]
[[ 1  5 10  4 11]
 [22 21 11 10  1]]


In [6]:
import numpy as np

mat = np.zeros([3,2])
print mat

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [15]:
arr = np.array([0] * 10).reshape([5,2])
print arr

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [19]:
np.random.randn(10,2)

array([[ 1.24407453,  1.64963328],
       [ 1.64504786,  0.40711333],
       [ 1.57616408, -0.57250624],
       [ 1.42898842, -2.35601806],
       [ 0.79335637,  0.52080354],
       [-0.30421392, -0.59812304],
       [ 1.91206783,  0.61393018],
       [-1.55222511, -1.11941184],
       [ 0.76039496,  0.90885247],
       [-1.11305996,  0.67146076]])

In [25]:
a = np.array([[2.0, 1.0], [4.0, 2.0]])
b = np.array([[1.0, 1.0], [6.0, 3.0]])
print a + b
print a - b

print np.dot(a,b)

print a.dot(b).dot(a)

[[  3.   2.]
 [ 10.   5.]]
[[ 1.  0.]
 [-2. -1.]]
[[  8.   5.]
 [ 16.  10.]]
[[ 36.  18.]
 [ 72.  36.]]


In [29]:
np.random.seed(20200724)
X = np.random.randn(10,2)
print X

[[ 0.061722   -0.57419489]
 [-0.22935131  0.96591975]
 [ 0.26623205  0.43955315]
 [ 0.29570751  1.38297576]
 [-0.48006958 -0.25572763]
 [ 0.53592532 -0.15575423]
 [-1.35626278 -0.78728757]
 [ 0.19937479  1.08232194]
 [-1.27044623  0.30786437]
 [-0.1061809   0.57807686]]


In [40]:
X = np.arange(10)

# print X[:]
print X[::-1]
print X[4:]
print X[:7]
print X[4:7]
print X[1:8:2]

[9 8 7 6 5 4 3 2 1 0]
[4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[4 5 6]
[1 3 5 7]


In [50]:
x = np.random.randn(10)
print x

mask = x >= 0.0
print mask

print x[mask]

print x[x >= 0]

[ 1.23033735  1.40321851  0.09751056  0.31943049  0.07162876 -0.06184967
 -1.02262615 -0.46366925 -0.18000379 -1.18701191]
[ True  True  True  True  True False False False False False]
[ 1.23033735  1.40321851  0.09751056  0.31943049  0.07162876]
[ 1.23033735  1.40321851  0.09751056  0.31943049  0.07162876]


In [53]:
x = np.arange(9).reshape(3,3)
print x

print x.T

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [55]:
x = np.rndom.randn(3, 3)
print x

np.save('random.npy', x)

AttributeError: 'module' object has no attribute 'rndom'