In [5]:
import numpy as np
arr = np.array([1,5,10,4,11,22,21,11,10,1])
print arr

mat = arr.reshape([2,5])

print mat

[ 1  5 10  4 11 22 21 11 10  1]
[[ 1  5 10  4 11]
 [22 21 11 10  1]]


In [6]:
import numpy as np

mat = np.zeros([3,2])
print mat

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [15]:
arr = np.array([0] * 10).reshape([5,2])
print arr

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [19]:
np.random.randn(10,2)

array([[ 1.24407453,  1.64963328],
       [ 1.64504786,  0.40711333],
       [ 1.57616408, -0.57250624],
       [ 1.42898842, -2.35601806],
       [ 0.79335637,  0.52080354],
       [-0.30421392, -0.59812304],
       [ 1.91206783,  0.61393018],
       [-1.55222511, -1.11941184],
       [ 0.76039496,  0.90885247],
       [-1.11305996,  0.67146076]])

In [25]:
a = np.array([[2.0, 1.0], [4.0, 2.0]])
b = np.array([[1.0, 1.0], [6.0, 3.0]])
print a + b
print a - b

print np.dot(a,b)

print a.dot(b).dot(a)

[[  3.   2.]
 [ 10.   5.]]
[[ 1.  0.]
 [-2. -1.]]
[[  8.   5.]
 [ 16.  10.]]
[[ 36.  18.]
 [ 72.  36.]]


In [29]:
np.random.seed(20200724)
X = np.random.randn(10,2)
print X

[[ 0.061722   -0.57419489]
 [-0.22935131  0.96591975]
 [ 0.26623205  0.43955315]
 [ 0.29570751  1.38297576]
 [-0.48006958 -0.25572763]
 [ 0.53592532 -0.15575423]
 [-1.35626278 -0.78728757]
 [ 0.19937479  1.08232194]
 [-1.27044623  0.30786437]
 [-0.1061809   0.57807686]]


In [40]:
X = np.arange(10)

# print X[:]
print X[::-1]
print X[4:]
print X[:7]
print X[4:7]
print X[1:8:2]

[9 8 7 6 5 4 3 2 1 0]
[4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[4 5 6]
[1 3 5 7]


In [50]:
x = np.random.randn(10)
print x

mask = x >= 0.0
print mask

print x[mask]

print x[x >= 0]

[ 1.23033735  1.40321851  0.09751056  0.31943049  0.07162876 -0.06184967
 -1.02262615 -0.46366925 -0.18000379 -1.18701191]
[ True  True  True  True  True False False False False False]
[ 1.23033735  1.40321851  0.09751056  0.31943049  0.07162876]
[ 1.23033735  1.40321851  0.09751056  0.31943049  0.07162876]


In [53]:
x = np.arange(9).reshape(3,3)
print x

print x.T

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [59]:
x = np.random.randn(3, 3)
print x

np.save('random.npy', x)


[[ 1.19036889  1.02433084  0.36317407]
 [ 0.16052037  1.17757244  0.28948327]
 [ 0.50420148  1.54925218 -0.75115675]]


In [62]:
y = np.load('random.npy')
print y

[[ 1.19036889  1.02433084  0.36317407]
 [ 0.16052037  1.17757244  0.28948327]
 [ 0.50420148  1.54925218 -0.75115675]]


In [66]:
x = np.loadtxt('hoge.csv', delimiter=',')

print x

np.savetxt('foo.csv', x, delimit=',')


[[  2.00000000e-01   3.39800000e+00   5.92000000e+02]
 [  1.30000000e+00   8.30000000e-01   8.80000000e+00]]


TypeError: savetxt() got an unexpected keyword argument 'delimit'

In [79]:
x = np.random.randn(3, 3)
print x

print x.dtype
print x.shape
print x.size
y = np.arange(8).reshape(2,2,2)
print y
print y.dtype
print y.size

[[  6.95345417e-01   3.55470041e-01   9.06984070e-04]
 [  3.12525860e-01  -1.02148466e+00   4.43637916e-01]
 [  2.66057539e-01  -7.34925701e-01   9.76428046e-01]]
float64
(3, 3)
9
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
int64
8


In [88]:
x = np.arange(9).reshape(3,3)
print x
print x.mean(1)
print x.mean(0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 1.  4.  7.]
[ 3.  4.  5.]


In [94]:
x = np.arange(1, 17).reshape(4, 4)
print x
print np.add(x, 1)

print x+1
print np.negative(x)

print np.power(x, 2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
[[ -1  -2  -3  -4]
 [ -5  -6  -7  -8]
 [ -9 -10 -11 -12]
 [-13 -14 -15 -16]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]
 [169 196 225 256]]


In [107]:
x = np.random.randint(0, 100, 10)
print x
y = np.random.randint(0, 100, (4,4))
print y

x.sort()
print x
# np.sort(x)

y1 = np.array(y)
y2 = np.array(y)
print y1
y1.sort(1)
print y1

[33  2 70 96  3 70 21 89 23 12]
[[10 36 33  3]
 [72 73 27 83]
 [28 45 36 16]
 [90 89 41 42]]
[ 2  3 12 21 23 33 70 70 89 96]
[[10 36 33  3]
 [72 73 27 83]
 [28 45 36 16]
 [90 89 41 42]]
[[ 3 10 33 36]
 [27 72 73 83]
 [16 28 36 45]
 [41 42 89 90]]


In [120]:
np.random.seed(20200724)
x = np.random.randint(0, 4, 10)
print x

print np.unique(x)

a = np.arange(5)
b = np.arange(3,8)
print a
print b

print np.intersect1d(a, b)
print np.union1d(a, b)
print np.setxor1d(a,b)
print np.in1d(a, b)

[1 0 3 1 3 1 2 0 1 3]
[0 1 2 3]
[0 1 2 3 4]
[3 4 5 6 7]
[3 4]
[0 1 2 3 4 5 6 7]
[0 1 2 5 6 7]
[False False False  True  True]


In [129]:
x = np.arange(1, 4)
print x
print np.linalg.norm(x)
diag_x = np.diag(x)
print diag_x
print np.linalg.det(diag_x)
print np.linalg.inv(diag_x)

e = np.eye(3)
print e
print np.dot(diag_x, e)
print np.trace(diag_x)

print np.linalg.eig(diag_x)

a = np.array([[2,1,1], [4,6,3], [8,8,9]])
b = np.array([[15], [41], [83]])
print np.linalg.solve(a,b)

[1 2 3]
3.74165738677
[[1 0 0]
 [0 2 0]
 [0 0 3]]
6.0
[[ 1.          0.          0.        ]
 [ 0.          0.5         0.        ]
 [ 0.          0.          0.33333333]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  3.]]
6
(array([ 1.,  2.,  3.]), array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]]))
[[ 5.]
 [ 2.]
 [ 3.]]


In [141]:
binomial = np.random.binomial(10, 0.5, (2,2))
print binomial

normal = np.random.normal(0,1, (2,2))
print normal

beta = np.random.beta(1, 1, (2,2))
print beta

chisquare = np.random.chisquare(1, (2,2))
print chisquare

[[3 3]
 [4 6]]
[[-0.65598467 -1.48684248]
 [ 0.18254007 -2.144666  ]]
[[ 0.79758514  0.15030161]
 [ 0.75776958  0.37781731]]
[[ 0.30206992  3.68702533]
 [ 0.49593079  3.10366002]]


In [147]:
x = np.random.randint(0, 10, (3,3))
y = np.random.randint(0, 10, (3,3))
print x
print y

print np.concatenate((x,y), axis=0)

print np.dstack((x,y))

x1, x2, x3 = np.split(x, (1,2))
print x1

[[0 7 9]
 [0 0 6]
 [4 5 6]]
[[8 6 7]
 [7 0 7]
 [7 5 0]]
[[0 7 9]
 [0 0 6]
 [4 5 6]
 [8 6 7]
 [7 0 7]
 [7 5 0]]
[[[0 8]
  [7 6]
  [9 7]]

 [[0 7]
  [0 0]
  [6 7]]

 [[4 7]
  [5 5]
  [6 0]]]
[[0 7 9]]


In [151]:
x = np.arange(9).reshape(3,3)
print x

print x.flatten()
print x.ravel()

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


In [155]:
x = np.array([3,6,9]).repeat(4)
print x
y=np.tile([7,2,4], 3)
print y

z=np.tile([7,2,4], (2,2))
print z



[3 3 3 3 6 6 6 6 9 9 9 9]
[7 2 4 7 2 4 7 2 4]
[[7 2 4 7 2 4]
 [7 2 4 7 2 4]]
