In [5]:
import numpy as np
arr = np.array([1,5,10,4,11,22,21,11,10,1])
print arr

mat = arr.reshape([2,5])

print mat

[ 1  5 10  4 11 22 21 11 10  1]
[[ 1  5 10  4 11]
 [22 21 11 10  1]]


In [6]:
import numpy as np

mat = np.zeros([3,2])
print mat

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
